title:            Legion Programming System
tagline:          A data-centric approach to parallel programming 
description:      Home page for the Legion parallel programming system

# Owner/author information
owner:
  name:           Legion
  bio:            A Data-Centric Parallel Programming System
  email:          #legiondiscuss@googlegroups.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:        
  facebook:       
  github: StanfordLegion/legion        
  linkedin:       
  instagram:      
  lastfm:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    

# Analytics and webmaster tools stuff goes here
google_analytics: UA-20524102-3   

# Links to include in top navigation
# For external links add external: true
links:
  - title: Overview 
    url: /overview/
  - title: Getting Started 
    url: /starting/
  - title: Tutorials
    url: /tutorial/
  - title: Events
    url: /events/
  - title: Documentation
    url: /documentation/
  - title: Publications
    url: /publications/
  - title: Resources
    url: /resources/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Los_Angeles
highlighter: rouge
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title.html

kramdown:
  auto_ids: true

exclude: ["Doxyfile", "Gemfile", "Gemfile.lock", "LICENSE.txt", "Makefile", "README.md"]
